# This extend our general Ruff rules specifically for tests
extend = "../pyproject.toml"

lint.extend-ignore = [
    "T201", # examples are allowed to use print statements
    "S101", # examples can be tested with assertions
]
