---
name: Linting

# yamllint disable-line rule:truthy
on:
  # push:
  pull_request:
  workflow_dispatch:

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4.2.2
      - name: 🏗 Set up UV
        uses: astral-sh/setup-uv@v6.4.3
        with:
          version: "latest"
          enable-cache: true
      - name: 🏗 Install project dependencies
        run: uv sync --all-extras --dev
      - name: 🚀 Run ruff linter
        run: uv run ruff check --output-format=github .
      - name: 🚀 Run ruff formatter
        run: uv run ruff format --check .

  pre-commit-hooks:
    name: Pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4.2.2
      - name: 🏗 Set up UV
        uses: astral-sh/setup-uv@v6.4.3
        with:
          version: "latest"
          enable-cache: true
      - name: 🏗 Install project dependencies
        run: uv sync --all-extras --dev
      - name: 🚀 Check Python AST
        run: uv run pre-commit run check-ast --all-files
      - name: 🚀 Check for case conflicts
        run: uv run pre-commit run check-case-conflict --all-files
      - name: 🚀 Check docstring is first
        run: uv run pre-commit run check-docstring-first --all-files
      - name: 🚀 Check that executables have shebangs
        run: uv run pre-commit run check-executables-have-shebangs --all-files
      - name: 🚀 Check JSON files
        run: uv run pre-commit run check-json --all-files
      - name: 🚀 Check for merge conflicts
        run: uv run pre-commit run check-merge-conflict --all-files
      - name: 🚀 Check for broken symlinks
        run: uv run pre-commit run check-symlinks --all-files
      - name: 🚀 Check TOML files
        run: uv run pre-commit run check-toml --all-files
      - name: 🚀 Check XML files
        run: uv run pre-commit run check-xml --all-files
      - name: 🚀 Check YAML files
        run: uv run pre-commit run check-yaml --all-files
      - name: 🚀 Detect Private Keys
        run: uv run pre-commit run detect-private-key --all-files
      - name: 🚀 Check End of Files
        run: uv run pre-commit run end-of-file-fixer --all-files
      - name: 🚀 Trim Trailing Whitespace
        run: uv run pre-commit run trailing-whitespace --all-files
