---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yaml
  workflow_dispatch:

jobs:
  labels:
    name: ♻️ Sync labels
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4.2.2
      - name: 🚀 Run Label Syncer
        uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
